apiVersion: v1
kind: Service
metadata:
  name: {{ include "base.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.container.port }}
      name: {{ .Values.service.name }}
  selector:
    {{- include "base.selectorLabels" . | nindent 4 }}
