# This YAML file will hold Helm chart values that apply to all environments and will override default template values
template:
  package: helm-base-services
  version: 0.0.3
image:
  repository: 909517579108.dkr.ecr.eu-west-2.amazonaws.com
  dockerName: api-flask-1

route:
  enabled: false

secrets:
  SQLALCHEMY_DATABASE_URI: "mysql+pymysql://root:secretpassword@my-release-mysql/app_database"

istio:
  enabled: true
  hosts:
    - host: api-sandbox.poc.blue1sky.me
      paths:
        - "/"

probe:
  readiness:
    initialdelay: 30
    port: 5000
    path: /
  liveness:
    initialdelay: 30
    port: 5000
    path: /
