# This YAML file will hold Helm chart values that apply to all environments and will override default template values
template:
  package: helm-base-services
  version: 0.0.2
image:
  repository: 909517579108.dkr.ecr.eu-west-2.amazonaws.com
  dockerName: api-flask-1

route:
  enabled: false

secrets:
  SQLALCHEMY_DATABASE_URI: "'mysql://root:secretpassword@my-release-mysql/app_database"


probe:
  readiness:
    initialdelay: 30
    port: 5000
    path: /healthcheck/
  liveness:
    initialdelay: 30
    port: 5000
    path: /healthcheck/
