apiVersion: v2
appVersion: v2
description: This Helm chart is used as a template to create backend service specific
  charts in OC.
home: https://github.com/tpaxle/helm-templates
keywords:
- deployment
- service
- horizontaolpodautoscaler
- template
maintainers:
- name: Demo
  url: https://github.com/tpaxle
name: api-flask-1
version: v0.0.2
appversion: v0.0.2
