name: CReate environment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'helm-base-istio'
        required: true
        default: '0.0.13'
      action:
        description: 'Action to deploy (ciapply, ciplan, validadte)'
        required: true
        default: 'ciapply'
env:
  PROJECT_NAME: "api-flask-1"
  AWS_ACCESS_KEY_ID:  ${{   secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{   secrets.AWS_SECRET_ACCESS_KEY }}
  PROXY_ENABLE: true
  PRERELEASE: ${{ secrets.PRERELEASE }}
jobs:
  init-environment:
    runs-on: ubuntu-latest #linux-platform # linux-platform, ubuntu-latest
  

    steps:
    - uses: actions/checkout@v2

    ###################################################
    ###################################################
    - name: HashiCorp - Setup Terraform
      # You may pin to the exact commit or the version.
      # uses: hashicorp/setup-terraform@15ba5bd056f1f2406e37023ca22c75ca08ceeb6e
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_version: "1.0.11"

    - name: AWS cli install action
      # You may pin to the exact commit or the version.
      # uses: chrislennon/action-aws-cli@1347f1da2852be38fdbea5e6e336f1e297fec7a0
      uses: chrislennon/action-aws-cli@1.1

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v1

  ###################################################
  ###################################################

    - name: Install Init chart Istio in Dev environment
      env:
        CHART_VERSION: ${{env.RELEASE_VERSION}}
        ECR: "909517579108.dkr.ecr.eu-west-2.amazonaws.com"
        HELM_EXPERIMENTAL_OCI: 1 
      run: |
        aws ecr get-login-password --region eu-west-2 | helm registry login \
          --username AWS --password-stdin ${{env.ECR}}
        aws eks --region eu-west-2 update-kubeconfig --name platf5-eks-main-s1
        helm pull oci://${{ env.ECR }}/helm-base-istio --version ${{github.event.inputs.version}}  --untar --insecure-skip-tls-verify
        ls -al
        helm upgrade --install ${{ env.PROJECT_NAME }} helm-base-istio/ --version ${{github.event.inputs.version}}  \
          --insecure-skip-tls-verify \
          --set replicaCount=1 \
          --history-max 3